runtime:
    epochs: 5
    rounds: 70
    lr: 0.01
    reg: 0.0
    momentum: 0.5
    random_seed: 12345
    batch_size: 15
    test_batch_size: 10
    server_w0_batch_size: 50
    public_data_percentage: 30 # Portion of data that will be shared with the server
    mnist_data_percentage: 30 # Out of 100, how much of data is imported
    mnist_normal_users_num: 10 # Neither eavesdroppers nor trusted users
    mnist_eavesdropper_num: 20 # Eavesdroppers
    mnist_trusted_users_num: 10 # Trusted
    femnist_users_num: 30 # Total users participating in training and are compared with w0 model
    femnist_eavesdropper_num: 5 # Out of femnist_users_num
    save_model: False
    W0_pure_path: "/home/ubuntu/FederatedLearning/data_output/20201108_225254_mnist_w0_SAN_125/models/server_model_49"
data:
    MNIST_PATH: "/home/ubuntu/data/MNIST"
    EMNIST_PATH: "/home/ubuntu/data/EMNIST/"
    FEMNIST_PATH: "/home/ubuntu/data/leaf_non_iid/data/femnist/data"
    EMNIST_GOOGLE_PATH: "/home/ubuntu/data/fed_google"
log:
    level: INFO
    interval: 5
    root_output_dir: "data_output"
    neptune_init: "ehsan/sandbox"
    neptune_exp: "evaluation_01"
