runtime:
    epochs: 10
    rounds: 250
    lr: 0.01
    momentum: 0.5
    batch_size: 20
    random_seed: 12345
    weight_decay: 0.0
    test_batch_size: 20
    use_cuda: False
server:
    data_fraction: 30 # Fraction of data that will be shared with the server
    save_model: False
mnist:
    shards_num: 200 # With 200 shards, there would be 300 samples per each shards
    shards_per_worker_num: 2
    selected_users_num: 10 
    total_users_num: 100 # Total number of users to partion data among them
    path: "/home/ubuntu/data/MNIST"
femnist:
    # femnist_users_num: 30 # Total users participating in training and are compared with w0 model
    # femnist_trusted_num: 0 # Out of femnist_users_num
    # femnist_eavesdropper_num: 0 # Out of femnist_users_num
data:
    EMNIST_PATH: "/home/ubuntu/data/EMNIST/"
    FEMNIST_PATH: "/home/ubuntu/data/leaf_non_iid/data/femnist/data"
    EMNIST_GOOGLE_PATH: "/home/ubuntu/data/fed_google"
log:
    level: INFO
    interval: 2
    format: '%(asctime)s: %(message)s'
    root_output_dir: "data_output"
    neptune_init: "ehsan/sandbox"
    neptune_exp: "evaluation_01"
